version: '3'
services:
  api:
    build: .
    container_name: burger-api
    networks:
      - private
    command: npm start
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:4.2
    container_name: burger-api-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - private

volumes:
  mongo-data:

networks:
  private:
