export { default as setup } from './routes/setup.route'
export { default as auth } from './routes/auth.route'
export { default as user } from './routes/user.route'
export { default as product } from './routes/product.route'
export { default as menu } from './routes/menu.route'
export { default as order } from './routes/order.route'
